Repository latticejs/lattice, pull requests merged in 2018-07, with the labels that each got.

#99 dag: add remove hooks with custom UI (panels)
  packages/dag/README.md
  packages/dag/src/dag.js
  packages/dag/src/edge.js
  packages/dag/src/index.js
  packages/dag/src/node.js
  packages/dag/src/panel.js
  packages/dag/stories/index.js
  packages/dag/test/__snapshots__/storyshot.test.js.snap
  packages/dag/test/enzyme.test.js
Labels: @latticejs/dag

#101 dag: Fix for node add action (missing x, y coordinates)
  packages/dag/src/index.js
  packages/dag/test/enzyme.test.js
Labels: @latticejs/dag, bug

#108 dag: fix mouse coords (svg <--> dom)
  packages/dag/src/index.js
  packages/dag/test/enzyme.test.js
  packages/mui-recharts/test/__snapshots__/storyshot.test.js.snap
  packages/widgets/test/__snapshots__/storyshot.test.js.snap
Labels: @latticejs/dag

#109 Greenkeeper/default/babel eslint 8.2.6
  packages/dag/package.json
  packages/mui-recharts/package.json
  packages/recharts-sunburst/package.json
  packages/widgets/package.json
Labels: greenkeeper

#110 chore(package): update eslint to version 5.0.1
  package.json
Labels: greenkeeper

#113 dag: tweaks around config for static graph
  packages/dag/src/dag.js
  packages/dag/src/edge.js
  packages/dag/test/__snapshots__/storyshot.test.js.snap
Labels: @latticejs/dag

#116 Greenkeeper/default/rollup 0.63.2
  packages/dag/package.json
  packages/mui-recharts/package.json
  packages/recharts-sunburst/package.json
  packages/widgets/package.json
Labels: greenkeeper

#120 clap: refactor download task
  packages/clap/lib/index.js
  packages/clap/lib/messages.js
  packages/clap/lib/tasks/downloadExample.js
  packages/clap/lib/tasks/index.js
  packages/clap/lib/tasks/validateExampleName.js
  packages/clap/package.json
  packages/clap/test/lib.test.js
  yarn.lock
Labels: CLI

#119 dag: add custom idx fn
  packages/dag/src/dag.js
  packages/dag/src/edge.js
  packages/dag/src/index.js
  packages/dag/src/node.js
  packages/dag/src/panel.js
  packages/dag/test/__snapshots__/storyshot.test.js.snap
Labels: @latticejs/dag

#123 clap: switch from linux mkdir to a lib wrapper for "better" OS interop
  packages/clap/lib/tasks/createDir.js
  packages/clap/package.json
  yarn.lock
Labels: CLI

#126 clap: add rename pkg name task
  packages/clap/lib/index.js
  packages/clap/lib/messages.js
  packages/clap/lib/tasks/index.js
  packages/clap/lib/tasks/renamePkgName.js
  packages/clap/test/lib.test.js
Labels: CLI

#121 Docs: add getting started info
  README.md
Labels: documentation

#129 clap: add new bin (create-lattice-app) + add missing dep
  packages/clap/package.json
  yarn.lock
Labels: CLI

#131 clap: fix clap usage (npx related)
  README.md
  packages/clap/README.md
Labels: CLI

#132 examples: add minimal lattice example
  examples/basic/.gitignore
  examples/basic/package-lock.json
  examples/basic/package.json
  examples/basic/public/favicon.ico
  examples/basic/public/index.html
  examples/basic/public/manifest.json
  examples/basic/src/App.js
  examples/basic/src/index.js
Labels: examples

#133 docs: mention alpha channel usage on install
  README.md
  packages/clap/README.md
Labels: documentation

#139 examples: improvements around basic example
  examples/basic/src/App.js
  examples/basic/src/Main.js
  examples/basic/src/index.js
Labels: enhancement, examples

#146 widgets: add docs!
  packages/widgets/README.md
  yarn.lock
Labels: @latticejs/widgets, documentation

#145 infinite-list: add doc with storybook-readme support
  .storybook/addons.js
  package.json
  packages/infinite-list/.storybook/addons.js
  packages/infinite-list/README.md
  packages/infinite-list/__mocks__/storybook-readme.js
  packages/infinite-list/package.json
  packages/infinite-list/stories/list.js
  packages/infinite-list/stories/table.js
  packages/infinite-list/stories/utils.js
  yarn.lock
Labels: @latticejs/infinite-list, documentation
