Repository latticejs/lattice, pull requests merged in 2018-11, with the labels that each got.

#251 Greenkeeper/husky 1.1.2
  package.json
  yarn.lock
Labels: greenkeeper

#252 Greenkeeper/prettier 1.14.3
  package.json
  yarn.lock
Labels: greenkeeper

#255 Packages: new build system & updates.
  package.json
  packages/clap/.babelrc
  packages/dag/.babelrc
  packages/dag/.storybook/config.js
  packages/dag/package.json
  packages/dag/rollup.config.js
  packages/dag/taskfile.js
  packages/infinite-list/.babelrc
  packages/infinite-list/.storybook/config.js
  packages/infinite-list/List.js
  packages/infinite-list/ScrollLoader.js
  packages/infinite-list/Table.js
  packages/infinite-list/TableOrderCell.js
  packages/infinite-list/TableSearchCell.js
  packages/infinite-list/lattice-scripts.config.js
  packages/infinite-list/package.json
  packages/infinite-list/taskfile.js
  packages/lattice-scripts/README.md
  packages/lattice-scripts/bin/lattice-scripts
  packages/lattice-scripts/cli.js
  packages/lattice-scripts/index.js
  packages/lattice-scripts/package.json
  packages/lattice-scripts/rollup.config.js
  packages/lattice-scripts/src/commands/build.js
  packages/lattice-scripts/src/commands/index.js
  packages/lattice-scripts/src/lib/build.js
  packages/lattice-scripts/src/lib/index.js
  packages/mui-recharts/.babelrc
  packages/mui-recharts/.storybook/config.js
  packages/mui-recharts/package.json
  packages/mui-recharts/test/__snapshots__/storyshot.test.js.snap
  packages/recharts-sunburst/.babelrc
  packages/recharts-sunburst/.storybook/config.js
  packages/recharts-sunburst/index.js
  packages/recharts-sunburst/package.json
  packages/tree/.babelrc
  packages/tree/.storybook/config.js
  packages/tree/index.js
  packages/tree/package.json
  packages/tree/taskfile.js
  packages/tree/test/__snapshots__/storyshot.test.js.snap
  packages/widgets/.babelrc
  packages/widgets/.storybook/config.js
  packages/widgets/Loader.js
  packages/widgets/SideMenu.js
  packages/widgets/Widget.js
  packages/widgets/index.js
  packages/widgets/lattice-scripts.config.js
  packages/widgets/package.json
  packages/widgets/taskfile.js
  packages/widgets/test/__snapshots__/storyshot.test.js.snap
  yarn.lock
Labels: enhancement

#256 Release from travis
  .travis.yml
  CHANGELOG.md
  RELEASE.md
  package.json
  yarn.lock
Labels: enhancement

#263 Update: minimal example to babel 7
  examples/minimal/.babelrc
  examples/minimal/package.json
Labels: enhancement, examples

#264 docs: move from alpha channel to beta
  README.md
  packages/clap/README.md
  packages/lattice-scripts/README.md
Labels: documentation

#265 examples: fix bad widget import (minimal)
  examples/minimal/src/App.js
Labels: bug, examples

#271 Fix: eslint warnings
  examples/dag-in-action/src/App.js
  packages/dag/src/index.js
  packages/dag/src/node.js
Labels: enhancement

#274 Update: normalize start script
  CHANGELOG.md
  examples/apollo-enterprise/package.json
  examples/apollo-real-time-chart/package.json
  examples/dag-in-action/package.json
Labels: enhancement

#278 examples: use named imports
  CHANGELOG.md
  examples/apollo-enterprise/src/components/dashboard/AverageRevenue.js
  examples/apollo-enterprise/src/components/dashboard/Demographic.js
  examples/apollo-enterprise/src/components/dashboard/NewCustomers.js
  examples/apollo-enterprise/src/components/dashboard/Stats.js
  examples/apollo-enterprise/src/components/dashboard/TaskScheduler.js
  examples/apollo-enterprise/src/components/dashboard/TopProducts.js
  examples/apollo-enterprise/src/components/employees/Form.js
  examples/apollo-enterprise/src/containers/Main.js
  examples/apollo-enterprise/src/containers/theme/General.js
  examples/apollo-enterprise/src/containers/theme/Widgets.js
  examples/apollo-real-time-chart/src/components/CPUUsage.js
  examples/apollo-real-time-chart/src/components/DisksUsage.js
  examples/apollo-real-time-chart/src/components/MemoryUsage.js
  examples/apollo-real-time-chart/src/components/ProcessUsage.js
  examples/basic/src/App.js
Labels: enhancement, examples

#281 example: dag-in-action height grows indefinitely on FF
  CHANGELOG.md
  examples/dag-in-action/src/App.js
Labels: bug, examples
