Repository latticejs/lattice, pull requests merged in 2018-09, with the labels that each got.

#190 Packages: Readme storybook addon for components.
  .gitignore
  package.json
  packages/dag/.storybook/addons.js
  packages/dag/README.md
  packages/dag/package.json
  packages/dag/stories/index.js
  packages/infinite-list/package.json
  packages/infinite-list/stories/list.js
  packages/infinite-list/stories/table.js
  packages/infinite-list/stories/utils.js
  packages/mui-recharts/.storybook/addons.js
  packages/mui-recharts/README.md
  packages/mui-recharts/package.json
  packages/mui-recharts/stories/basic.js
  packages/mui-recharts/stories/index.js
  packages/recharts-sunburst/README.md
  packages/recharts-sunburst/package.json
  packages/recharts-sunburst/stories/index.js
  packages/storybook-readme/README.md
  packages/storybook-readme/package.json
  packages/storybook-readme/rollup.config.js
  packages/storybook-readme/src/main.js
  packages/storybook-readme/test/__mocks__/storybook-readme.js
  packages/storybook-readme/test/storybook-readme.test.js
  packages/tree/.storybook/addons.js
  packages/tree/README.md
  packages/tree/package.json
  packages/tree/stories/tree.js
  packages/widgets/.storybook/addons.js
  packages/widgets/README.md
  packages/widgets/package.json
  packages/widgets/stories/loader.js
  packages/widgets/stories/sidemenu.js
  packages/widgets/stories/widget.js
  yarn.lock
Labels: enhancement

#193 Packages: improving widget component
  .travis.yml
  examples/apollo-real-time-chart/package.json
  examples/apollo-real-time-chart/src/components/CPUInfo.js
  examples/apollo-real-time-chart/src/components/CPUUsage.js
  examples/apollo-real-time-chart/src/components/DisksUsage.js
  examples/apollo-real-time-chart/src/components/MemoryUsage.js
  examples/apollo-real-time-chart/src/components/OSInfo.js
  examples/apollo-real-time-chart/src/components/ProcessUsage.js
  examples/apollo-real-time-chart/src/components/Widget.js
  packages/widgets/src/Widget.js
  packages/widgets/stories/widget.js
  packages/widgets/test/__snapshots__/storyshot.test.js.snap
Labels: @latticejs/widgets, enhancement

#194 dag: fix dag d3-react changes on new props
  packages/dag/package.json
  packages/dag/src/dag.js
  packages/dag/src/index.js
  packages/dag/src/node.js
  packages/dag/stories/index.js
  packages/dag/test/__snapshots__/storyshot.test.js.snap
  yarn.lock
Labels: @latticejs/dag, bug

#195 Greenkeeper/default/monorepo.enzyme 1.5.0
  packages/dag/package.json
  packages/infinite-list/package.json
  packages/mui-recharts/package.json
  packages/recharts-sunburst/package.json
  packages/widgets/package.json
Labels: greenkeeper

#196 Greenkeeper/default/rollup plugin babel 4.0.3
  packages/dag/package.json
  packages/infinite-list/package.json
  packages/mui-recharts/package.json
  packages/recharts-sunburst/package.json
  packages/widgets/package.json
Labels: greenkeeper

#197 Greenkeeper/default/@material ui/icons 3.0.1
  packages/infinite-list/package.json
  packages/widgets/package.json
Labels: greenkeeper

#198 Storybook: Fix bad webpack import
  .storybook/webpack.config.js
  packages/dag/src/index.js
  packages/storybook-readme/package.json
Labels: @latticejs/lattice, bug

#200 dag: add fill property to dag edge class
  packages/dag/src/index.js
Labels: @latticejs/dag, bug

#201 Packages: update dependencies
  examples/apollo-enterprise/package.json
  examples/apollo-real-time-chart/package.json
  examples/basic/package.json
  examples/minimal/package.json
  packages/dag/package.json
  packages/infinite-list/package.json
  packages/mui-recharts/package.json
  packages/react-scripts/package.json
  packages/recharts-sunburst/package.json
  packages/tree/package.json
  packages/tree/test/__snapshots__/storyshot.test.js.snap
  packages/widgets/package.json
  yarn.lock
Labels: @latticejs/lattice, enhancement, greenkeeper

#210 Storybook: Build docs public version
  .storybook/webpack.config.js
  docs/iframe.html
  docs/index.html
  docs/static/manager.31c3893c69fc06b467f7.bundle.js
  docs/static/manager.589cb1f363a71c775ec8.bundle.js
  docs/static/manager.764d2ec3399e03276dca.bundle.js
  docs/static/preview.af3fe12ba3ac3737be30.bundle.js
  docs/static/preview.bf7508bdde9c5250d8ae.bundle.js
  docs/static/preview.c20747929547d310475e.bundle.js
  packages/dag/.storybook/webpack.config.js
  packages/infinite-list/.storybook/webpack.config.js
  packages/mui-recharts/.storybook/webpack.config.js
  packages/recharts-sunburst/.storybook/webpack.config.js
  packages/tree/.storybook/webpack.config.js
  packages/widgets/.storybook/webpack.config.js
Labels: documentation

#212 Storybook: fix for local storybooks.
  packages/dag/.storybook/webpack.config.js
  packages/infinite-list/.storybook/webpack.config.js
  packages/mui-recharts/.storybook/webpack.config.js
  packages/recharts-sunburst/.storybook/webpack.config.js
  packages/tree/.storybook/webpack.config.js
  packages/widgets/.storybook/webpack.config.js
Labels: bug

#209 examples: new dag example
  examples/dag-in-action/.gitignore
  examples/dag-in-action/README.md
  examples/dag-in-action/package.json
  examples/dag-in-action/public/favicon.ico
  examples/dag-in-action/public/index.html
  examples/dag-in-action/public/manifest.json
  examples/dag-in-action/screen.png
  examples/dag-in-action/server/index.js
  examples/dag-in-action/src/App.js
  examples/dag-in-action/src/Main.js
  examples/dag-in-action/src/index.js
Labels: @latticejs/dag, examples

#215 Storybook: JSON Tree view story
  packages/tree/README.md
  packages/tree/src/child.js
  packages/tree/src/tree.js
  packages/tree/stories/json-icons.js
  packages/tree/stories/tree.js
  packages/tree/test/__snapshots__/storyshot.test.js.snap
Labels: @latticejs/tree, documentation, enhancement, new feature

#218 Storybook: Update public docs
  docs/iframe.html
  docs/index.html
  docs/static/manager.31c3893c69fc06b467f7.bundle.js
  docs/static/manager.7ccbbbb38e2fcc40b064.bundle.js
  docs/static/preview.af3fe12ba3ac3737be30.bundle.js
  docs/static/preview.c84b59f57003712e4b12.bundle.js
Labels: documentation

#221 dag: fix elements positions after coords system change
  packages/dag/README.md
  packages/dag/src/dag.js
  packages/dag/src/index.js
  packages/dag/src/node.js
  packages/dag/src/panel.js
  packages/dag/stories/index.js
  packages/dag/test/__snapshots__/storyshot.test.js.snap
  packages/dag/test/enzyme.test.js
Labels: @latticejs/dag, bug

#224 dag: fix test for onEdgeAdded cb
  packages/dag/test/enzyme.test.js
  packages/dag/test/shim.js
  yarn.lock
Labels: @latticejs/dag
